# Generated by Django 4.0 on 2021-12-27 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('plc_address', models.CharField(max_length=100)),
                ('plc_port', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('requested_amount', models.IntegerField()),
                ('completed_amount', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interfaces.interface')),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=255)),
                ('protocol_id', models.CharField(default='0000', max_length=4)),
                ('length', models.CharField(default='0006', max_length=4)),
                ('unit_id', models.CharField(max_length=2)),
                ('function', models.CharField(max_length=2)),
                ('starting_address', models.CharField(max_length=4)),
                ('data', models.CharField(blank=True, max_length=255, null=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interfaces.interface')),
            ],
        ),
    ]
