# Generated by Django 4.0 on 2021-12-24 13:50

from django.db import migrations, models
import django.db.models.deletion


def create_initial_interface(apps, schema_editor):
    Interface = apps.get_model('interfaces', 'Interface')
    Interface.objects.create(name='interface1', plc_address='127.0.1.101', plc_port=1024)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interfaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('plc_address', models.CharField(max_length=100)),
                ('plc_port', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('requested_amount', models.IntegerField()),
                ('completed_amount', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interfaces.interface')),
            ],
        ),
        migrations.RunPython(create_initial_interface),
    ]
