# Generated by Django 4.0 on 2021-12-27 18:05

from django.db import migrations


def create_initial_interface(apps, schema_editor):
    Interface = apps.get_model('interfaces', 'Interface')
    Interface.objects.create(name='interface1', plc_address='127.0.1.101', plc_port=1024)


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_interface),
    ]
