# Generated by Django 3.2.7 on 2021-12-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
