# Generated by Django 3.2.7 on 2021-12-26 13:55

from django.db import migrations, models





class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0003_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
