# Generated by Django 3.2.7 on 2021-12-26 14:08

from django.db import migrations


def create_initial_status_list(apps, schema_editor):
    Status = apps.get_model('interfaces', 'Status')
    for status in ['requested', 'completed', 'canceled']:
        Status.objects.create(status=status)


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0005_alter_status_options'),
    ]

    operations = [
        migrations.RunPython(create_initial_status_list),
    ]
