# Generated by Django 4.0 on 2021-12-27 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0006_auto_20211226_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=255)),
                ('protocol_id', models.CharField(default='0000', max_length=4)),
                ('length', models.CharField(default='0006', max_length=4)),
                ('unit_id', models.CharField(max_length=2)),
                ('function', models.CharField(max_length=2)),
                ('starting_address', models.CharField(max_length=4)),
                ('quantity', models.CharField(max_length=4)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interfaces.interface')),
            ],
        ),
    ]
