# Generated by Django 4.0 on 2021-12-29 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='command',
            unique_together={('interface', 'command')},
        ),
    ]
