# Generated by Django 4.0 on 2021-12-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0007_alter_command_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='completed_amount',
            field=models.IntegerField(default=0),
        ),
    ]
