# Generated by Django 4.0 on 2021-12-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0007_command'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='quantity',
        ),
        migrations.AddField(
            model_name='command',
            name='data',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
