# Generated by Django 4.0 on 2021-12-27 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0009_remove_command_quantity_command_data'),
        ('interfaces', '0010_fill_command_with_initial_data'),
    ]

    operations = [
    ]
